[package]
name = "konnekt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
flate2 = "1.0.27"

tokio = { version = "1", features = ["full"] }

